// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKAhfR3D14TLlLabj-dv43zg7r9YNx0w',
    appId: '1:811406590423:web:997d4e5a64dc08a2d8cb92',
    messagingSenderId: '811406590423',
    projectId: 'my-travaly',
    authDomain: 'my-travaly.firebaseapp.com',
    storageBucket: 'my-travaly.firebasestorage.app',
    measurementId: 'G-DFMKGWY57H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4aSOmS4tUzkYLcQbvNvKowWnj2aRX48',
    appId: '1:811406590423:android:e648c7db28f46eaad8cb92',
    messagingSenderId: '811406590423',
    projectId: 'my-travaly',
    storageBucket: 'my-travaly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA74mOYliqOPPwoDS-sQw7GG2RWCjuQy2I',
    appId: '1:811406590423:ios:1aa7ec56e49a9ec5d8cb92',
    messagingSenderId: '811406590423',
    projectId: 'my-travaly',
    storageBucket: 'my-travaly.firebasestorage.app',
    iosBundleId: 'com.example.myTravaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA74mOYliqOPPwoDS-sQw7GG2RWCjuQy2I',
    appId: '1:811406590423:ios:1aa7ec56e49a9ec5d8cb92',
    messagingSenderId: '811406590423',
    projectId: 'my-travaly',
    storageBucket: 'my-travaly.firebasestorage.app',
    iosBundleId: 'com.example.myTravaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBKAhfR3D14TLlLabj-dv43zg7r9YNx0w',
    appId: '1:811406590423:web:418b0b8fa74f4300d8cb92',
    messagingSenderId: '811406590423',
    projectId: 'my-travaly',
    authDomain: 'my-travaly.firebaseapp.com',
    storageBucket: 'my-travaly.firebasestorage.app',
    measurementId: 'G-3Z4KM3NXKH',
  );
}
